# Generated by Django 3.1.5 on 2021-01-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('important', 'important'), ('normal', 'normal'), ('not important', 'not important')], max_length=100)),
            ],
        ),
    ]
